In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from scipy import stats
import math
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
train = pd.read_csv('TrainClean.csv')
test = pd.read_csv('TestClean.csv')
train = train.drop(labels='Unnamed: 0', axis=1) #there is this new misterious and useless column
all_data_index = train.columns.drop(['NumberOfSales'])
all_data = pd.concat((train.loc[:,all_data_index],test.loc[:,all_data_index]))

In [3]:
numeric_variables=pd.DataFrame()
for col in all_data.columns:
    if (all_data[col].value_counts().index.isin([0,1]).all()==0): #if the column is not binary
        numeric_variables[col]=all_data[col]

In [4]:
numeric_variables.head()

,NearestCompetitor,Region_AreaKM2,Region_GDP,Region_PopulationK,CloudCover,Max_Dew_PointC,Max_Humidity,Max_Sea_Level_PressurehPa,Max_TemperatureC,Max_VisibilityKm,...,Mean_Sea_Level_PressurehPa,Mean_TemperatureC,Mean_VisibilityKm,Mean_Wind_SpeedKm_h,Min_Dew_PointC,Min_Humidity,Min_Sea_Level_PressurehPa,Min_TemperatureC,Min_VisibilitykM,Precipitationmm
0,326,9643,17130,2770,1000.0,1,100.0,1032,2,19.0,...,1030,1,11.0,16,-2,70,1029,1,6.0,0.0
1,326,9643,17130,2770,1000.0,0,87.0,1030,5,23.0,...,1027,3,13.0,10,-2,58,1025,1,10.0,0.0
2,326,9643,17130,2770,1000.0,0,81.0,1026,4,31.0,...,1024,3,11.0,10,-3,55,1023,2,8.0,0.0
3,326,9643,17130,2770,1000.0,-3,80.0,1027,8,31.0,...,1024,3,15.0,10,-6,25,1022,-1,10.0,0.0
4,326,9643,17130,2770,1000.0,-2,93.0,1024,11,31.0,...,1020,4,22.0,11,-4,26,1016,-2,16.0,0.0

Principal component analysis is affected by attribute scale so we normalize all the attributes by eliminating the mean and scaling to unit variance.

In [5]:
x = StandardScaler().fit_transform(numeric_variables)

In [19]:
n_components = 5
column_names = []
for i in range (0, n_components):
    col_name = "component {}".format(i+1);
    column_names.append(col_name)

In [20]:
pca = PCA(n_components)
new_data = pca.fit_transform(x)
pca_all_data = pd.DataFrame(data = new_data, 
                        columns = column_names)

In [21]:
print("Explained Variance")
for i in range (0, n_components):
    string = "component {} {}".format(i+1, pca.explained_variance_ratio_[i])
    print(string)
print("   Total Explained Variance %3.2f"%sum(pca.explained_variance_ratio_))

Explained Variance
component 1 0.2713414343178465
component 2 0.15425379418974214
component 3 0.14290450064912294
component 4 0.09116742396572225
component 5 0.06351193121023403
   Total Explained Variance 0.72

In [22]:
print("Components")
for i,c in enumerate(pca.components_):
    print("Component %d\t%s"%(i,str(c)))

Components
Component 0	[ 0.00524303  0.0614998   0.01445104  0.0066605  -0.00211693 -0.35217793
  0.12209576  0.02523689 -0.38489073 -0.13264459  0.02030514 -0.34702633
  0.22529865 -0.00256972 -0.3925278  -0.17975039  0.06730438 -0.33264421
  0.23530813 -0.02080838 -0.36817666 -0.16018428 -0.02077574]
Component 1	[-0.01416014 -0.04950546 -0.03079082 -0.01653942  0.00071035 -0.19813282
 -0.27523409  0.32682058 -0.00078368  0.10338633 -0.07861828 -0.21510295
 -0.332584    0.33261562 -0.06163204  0.2969181  -0.05966381 -0.22411662
 -0.29551112  0.32044719 -0.13879508  0.28506613 -0.23158764]
Component 2	[-0.02671798 -0.10460026 -0.02292548 -0.00122493  0.01101013 -0.11934613
 -0.26539922 -0.35368643 -0.05145331  0.18952337  0.33590308 -0.13627819
 -0.20155761 -0.38389961 -0.04816683  0.22153717  0.34291208 -0.14083967
 -0.14695343 -0.39331621 -0.04329435  0.22037668  0.06627396]
Component 3	[-0.20688024  0.54096269  0.46706324  0.57780419  0.08977412  0.01758759
 -0.02709682  0.03024734  0.06183224 -0.16813397  0.17732202  0.00368191
 -0.04166287  0.03098042  0.03628166 -0.05080591  0.12586605 -0.00899672
 -0.05759218  0.02661367  0.00868456  0.09627715 -0.0556881 ]
Component 4	[ 0.12074856  0.23137403 -0.02476477  0.00342411 -0.06637638 -0.06599187
 -0.00817542 -0.33223277  0.0721852  -0.26094514 -0.47127284 -0.06452386
 -0.12259055 -0.27719372  0.00214282  0.05295019 -0.47481351 -0.06690954
 -0.12244234 -0.23345759 -0.08525913  0.09541817 -0.31941187]

In [23]:
pca_all_data.head(5)

   component 1  component 2  component 3  component 4  component 5
0     3.243880     1.701923    -1.911056     0.158194    -1.623560
1     2.191409     2.776040    -1.007928     0.030726    -0.396283
2     2.091733     2.563472    -0.060951    -0.001038    -0.706402
3     1.757692     4.219805     0.745435     0.084325     0.078920
4     1.358421     3.553074     1.406075     0.160967     0.226487